[build]
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions]
  # Erhöhtes Zeitlimit für KI-Modellanalysen
  node_bundler = "esbuild"

[functions.analyze-hair]
  timeout = 60

[functions.send-analysis-result]
  timeout = 30

[functions.send-email]
  timeout = 30

[functions.contact-form]
  timeout = 30

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Header für Caching
[[headers]]
  # Cache statische Assets für 1 Jahr
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache andere statische Dateien (Bilder, Schriften etc.) auch für 1 Jahr
  for = "/*.?(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Verhindere Caching für HTML-Dateien
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Verhindere Caching für die Root-HTML (falls /index.html nicht direkt aufgerufen wird)
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"